version: "3.8"

services:
  vpn-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-agent
    command: ["${UUID}"]
    network_mode: bridge
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .helium-agent:/app/.helium-agent
